version: '3.3'

volumes:
  certificate:
    driver: local

services:
  traefik:
    image: traefik:2.3
    container_name: traefik
    restart: always

    env_file:
      - /data/environment/.env

    command:
      - "--log.level=DEBUG"
      - "--api"
      - "--pilot.token=${PILOT}"
      - "--providers.docker=true"
      - "--providers.docker.network=traefik"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--certificatesresolvers.tmp.acme.httpchallenge=true"
      - "--certificatesresolvers.tmp.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.tmp.acme.email=hello@undefinedtea.dev"
      - "--certificatesresolvers.tmp.acme.storage=/certificate/acme.json"

    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`api-pilot.undefinedtea.com`)
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.middlewares=api
      - traefik.http.routers.traefik.tls.certresolver=tmp
      - traefik.http.middlewares.api.basicauth.users=${API}:${API_}

    ports:
      - 80:80
      - 443:443
      - '22:22'

    networks:
      - default

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - certificate:/certificate

networks:
  default:
    external:
      name: traefik
